/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Maquina;

import NegocioException.NegocioException;
import dto.ComputadoraDTO;
import dto.PrestamoComputadoraDTO;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;
import negocio.IAlumnoNegocio;
import negocio.IComputadoraNegocio;
import negocio.IPrestamoComputadoraNegocio;

/**
 *
 * @author Oley
 */
public class EquipoDisponible extends javax.swing.JFrame {

    
    private String rutaITSONLogo = "src/main/java/Imagenes/CaballoPotros_1.png";
    private String rutaPotrosLogo = "src/main/java/Imagenes/ItsonLogoPNG_1.png";
    private String ip;
    private static ComputadoraDTO compu;
    private static boolean detener = false;
    
    
    IComputadoraNegocio computadoraNegocio;
    IAlumnoNegocio alumnoNegocio;
    IPrestamoComputadoraNegocio prestamoComputadoraNegocio;
    
    /**
     * Creates new form EquipoDisponible
     */
    public EquipoDisponible(IComputadoraNegocio computadoraNegocio, IAlumnoNegocio alumnoNegocio, IPrestamoComputadoraNegocio prestamoComputadoraNegocio) {
        this.prestamoComputadoraNegocio = prestamoComputadoraNegocio;
        this.alumnoNegocio = alumnoNegocio;
        this.computadoraNegocio = computadoraNegocio;
        
        initComponents();
        
        
        setImagenLabel(jblImagenITSON, rutaITSONLogo);
        setImagenLabel(jblPotros, rutaPotrosLogo);
        
        try {
            this.ip = obtenerIP();
        } catch (UnknownHostException ex) {
            Logger.getLogger(EquipoDisponible.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        metodoEjecutadorCada10Segundos();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumMaquina = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jblImagenITSON = new javax.swing.JLabel();
        jblPotros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido");

        txtNumMaquina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNumMaquina.setText("Computadora #1");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setText("Equipo Disponible");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(txtNumMaquina)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(txtNumMaquina)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jblPotros.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblImagenITSON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jblPotros, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jblImagenITSON, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblPotros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


     /**
     * Metodo que coloca una imagen en los parametros especificados en la interfaz
     * @param nombreJlb el jlabel que sera reemplazado por una imagen
     * @param ruta la direccion donde se encuentra la imagen
     */
    private void setImagenLabel(JLabel nombreJlb, String ruta){
    
        ImageIcon image = new ImageIcon(ruta);
        
        Icon icon = new ImageIcon(
        image.getImage().getScaledInstance(nombreJlb.getWidth(), nombreJlb.getHeight(), Image.SCALE_DEFAULT));
        
        nombreJlb.setIcon(icon);
        
        this.repaint();
   
    }
    
        
    
    public String obtenerIP() throws UnknownHostException {
        InetAddress ip = InetAddress.getLocalHost();
        return ip.getHostAddress(); 
    
        }

    
    
    public void metodoEjecutadorCada10Segundos(){


        
        ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);

        
        
            Runnable tarea = () -> {
            // Aquí va el código que deseas ejecutar cada 10 segundos
 
                System.out.println("Ejecutando tarea cada 10 segundos: " + System.currentTimeMillis());
                
            try {
                comprobacionDisponibilidad();
            } catch (NegocioException ex) {
                Logger.getLogger(EquipoDisponible.class.getName()).log(Level.SEVERE, null, ex);
            }


            };

            // Programa la tarea para que se ejecute cada 10 segundos, con un retraso inicial de 0 segundos
            scheduler.scheduleAtFixedRate(tarea, 0, 10, TimeUnit.SECONDS);
         
    }
    
    public void comprobacionDisponibilidad() throws NegocioException{
        
        compu = computadoraNegocio.obtenerPorIP(ip);
        System.out.println(compu.getIp());
        txtNumMaquina.setText("Numero de maquina #" + compu.getNumeroMaquina());
        
        List<PrestamoComputadoraDTO> prestamos = new ArrayList<>();
        
        System.out.println("compu" + compu.getId());
        System.out.println("lista " + prestamos.size());
        
        prestamos = prestamoComputadoraNegocio.buscarPrestamoPorComputadora(compu.getId());
        PrestamoComputadoraDTO elBueno = prestamos.get(prestamos.size() - 1);
        
        System.out.println("esta apartada " + elBueno.isSigueApartada());
        if(elBueno.isSigueApartada()){
            System.out.println("Entro a disponible");
            return;
            
            }
                        
        if(elBueno.isSigueApartada() == true){
            
            EquipoOcupado equipoOcupado = new EquipoOcupado(computadoraNegocio, alumnoNegocio, prestamoComputadoraNegocio);
            equipoOcupado.setVisible(true);
            this.dispose();
            detener = true;
            }
        
        compu = null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jblImagenITSON;
    private javax.swing.JLabel jblPotros;
    private javax.swing.JLabel txtNumMaquina;
    // End of variables declaration//GEN-END:variables

}
