/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import NegocioException.NegocioException;
import dto.AlumnoDTO;
import dto.BloqueoDTO;
import java.util.Date;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.IAlumnoNegocio;
import negocio.IBloqueoNegocio;

/**
 *
 * @author Oley
 */
public class AgregarBloqueo extends javax.swing.JFrame {

    
    private GestionBloqueos gestionBloqueos;
    private IAlumnoNegocio alumnoNegocio;
    private IBloqueoNegocio bloqueoNegocio;
    
    /**
     * Creates new form AgregarBloqueo
     */
    public AgregarBloqueo(GestionBloqueos gestion, IAlumnoNegocio alumnoNegocio, IBloqueoNegocio bloqueoNegocio, IAlumnoNegocio alumnoNegocio1) {
        this.gestionBloqueos = gestion;
        this.alumnoNegocio = alumnoNegocio;
        this.bloqueoNegocio = bloqueoNegocio;
        this.alumnoNegocio = alumnoNegocio;
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jblFechaLiberacion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jblFechaLiberacion1 = new javax.swing.JLabel();
        datePickerBloqueo = new com.github.lgooddatepicker.components.DatePicker();
        datePickerLiberacion = new com.github.lgooddatepicker.components.DatePicker();
        txtIdAlumno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Agregar un Bloqueo");

        jblFechaLiberacion.setText("Fecha Bloqueo:");

        jLabel3.setText("Alumno:");

        jLabel4.setText("Motivo:");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Bloquear");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jblFechaLiberacion1.setText("Fecha Liberacion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(datePickerBloqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jblFechaLiberacion1)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdAlumno)
                                    .addComponent(datePickerLiberacion, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                    .addComponent(txtMotivo, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRegresar)
                            .addGap(185, 185, 185)
                            .addComponent(btnAgregar))
                        .addComponent(jblFechaLiberacion)))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblFechaLiberacion)
                    .addComponent(datePickerBloqueo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblFechaLiberacion1)
                    .addComponent(datePickerLiberacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegresar)
                            .addComponent(btnAgregar))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        
        try{

        BloqueoDTO bloqueo = new BloqueoDTO();
             
        bloqueo.setAlumno(Long.valueOf(txtIdAlumno.getText()));
        bloqueo.setEliminado(false);
        
        LocalDate localDate = datePickerBloqueo.getDate();
        LocalDate localDate2 = datePickerLiberacion.getDate();
        
        
        Date date = Date.from(localDate.atStartOfDay(ZoneId.systemDefault()).toInstant());    
        Date date2 = Date.from(localDate2.atStartOfDay(ZoneId.systemDefault()).toInstant());    
        
        
        Calendar calendar = Calendar.getInstance();
        Calendar calendar2 = Calendar.getInstance();
        calendar.setTime(date);
        calendar2.setTime(date2);
        
        bloqueo.setFechaBloqueo(calendar);
        bloqueo.setFechaLiberacion(calendar2);
        bloqueo.setMotivo(txtMotivo.getText());

        
            System.out.println(bloqueo.toString());
            BloqueoDTO exito = new BloqueoDTO();
            
            exito = bloqueoNegocio.guardarBloqueo(bloqueo);
            System.out.println(exito.toString());
            JOptionPane.showMessageDialog(this, "El bloqueo se ha guardado");
            gestionBloqueos.setVisible(true);
            this.dispose();
            
        } 
        
        catch (NegocioException ex) {
            System.out.println("nose pudo agreagar bloqueo");
            Logger.getLogger(AgregarBloqueo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
        gestionBloqueos.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegresar;
    private com.github.lgooddatepicker.components.DatePicker datePickerBloqueo;
    private com.github.lgooddatepicker.components.DatePicker datePickerLiberacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jblFechaLiberacion;
    private javax.swing.JLabel jblFechaLiberacion1;
    private javax.swing.JTextField txtIdAlumno;
    private javax.swing.JTextField txtMotivo;
    // End of variables declaration//GEN-END:variables
}
