/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import dto.AlumnoDTO;
import negocio.IAlumnoNegocio;
import negocio.IBloqueoNegocio;
import negocio.ICarreraNegocio;
import negocio.ICentroComputoNegocio;
import negocio.IComputadoraNegocio;
import negocio.IUnidadNegocio;

/**
 *
 * @author Oley
 */
public class InicioSesionAlumno extends javax.swing.JFrame {
 private ICarreraNegocio carreraNegocio;
    private IUnidadNegocio unidadNegocio;
    private IAlumnoNegocio alumnoNegocio;
    private IBloqueoNegocio bloqueoNegocio;
    private ICentroComputoNegocio centroComputoNegocio;
    private IComputadoraNegocio computadoraNegocio;
    /**
     * Creates new form InicioSesionAlumno
     */
    public InicioSesionAlumno(IAlumnoNegocio alumnoNegocio) {
        this.alumnoNegocio=alumnoNegocio;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Iniciar Sesion Estudiante");

        jLabel2.setText("Id Alumno:");

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButton1)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String idAlumnoStr = jTextField1.getText().trim();

    if (idAlumnoStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresa un ID de alumno.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        long idAlumno = Long.parseLong(idAlumnoStr);
        AlumnoDTO alumno = alumnoNegocio.buscarAlumno(idAlumno);

        if (alumno != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Bienvenido, acceso concedido.");

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "ID de alumno no encontrado. Intenta nuevamente.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "El ID de alumno debe ser un número válido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al buscar el alumno: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
