/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import NegocioException.NegocioException;
import dto.CarreraDTO;
import dto.ReporteCarrera;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.IAlumnoNegocio;
import negocio.IBloqueoNegocio;
import negocio.ICarreraNegocio;
import negocio.IUnidadNegocio;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.data.JRMapCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Oley
 */
public class ReporteCarrerasFiltro extends javax.swing.JFrame {
private ICarreraNegocio carreraNegocio;
  private IBloqueoNegocio bloqueoNegocio;
    private IUnidadNegocio unidadNegocio;
    private IAlumnoNegocio alumnoNegocio;
    private InicioSesion inicioSesion;
    private Administrador administrador;
    /**
     * Creates new form ReporteCarrerasFiltro
     */
    public ReporteCarrerasFiltro(ICarreraNegocio carreraNegocio,IAlumnoNegocio alumnoNegocio) {
        this.carreraNegocio=carreraNegocio;
        this.alumnoNegocio=alumnoNegocio;
        initComponents();
    try {
        cargarCarreras();
    } catch (NegocioException ex) {
        Logger.getLogger(ReporteCarrerasFiltro.class.getName()).log(Level.SEVERE, null, ex);
    }
;
    }
  private void cargarCarreras() throws NegocioException {
            
        try {
            cbcCarreras.removeAllItems();
            List<CarreraDTO> carreraDTOs = carreraNegocio.obtenerTodos();
            for (CarreraDTO carreraDTO : carreraDTOs) {
                cbcCarreras.addItem(carreraDTO.getNombre());
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los centros " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbcCarreras = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reporte-Carreras");

        jLabel2.setText("Carreras:");

        cbcCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbcCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcCarrerasActionPerformed(evt);
            }
        });

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generar Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Selecionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carrera"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbcCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbcCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
MenuReportes menuReportes=new MenuReportes(administrador, bloqueoNegocio, alumnoNegocio, carreraNegocio);
menuReportes.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
        // Verificación de que hay datos en la tabla
        if (jTable2.getRowCount() > 0) {
            List<Map<String, ?>> listaReportes = new ArrayList<>();

            for (int i = 0; i < jTable2.getRowCount(); i++) {
                String nombreCarrera = (String) jTable2.getValueAt(i, 0);
                
                CarreraDTO carreraDTO = carreraNegocio.obtenerCarreraPorNombre(nombreCarrera);
                Long carreraId = carreraDTO.getId(); 
                
                Integer minutosUso = carreraNegocio.obtenerTiempoMaxUsoDiarioTotal(); 
                Long cantidadAlumnos = alumnoNegocio.contarAlumnos(); 

                Map<String, Object> datos = new HashMap<>();
                datos.put("nombreCarrera", nombreCarrera);
                datos.put("minutosUso", minutosUso);
                datos.put("cantidadAlumnos", cantidadAlumnos);

                listaReportes.add(datos);
            }

            InputStream reporteStream = getClass().getClassLoader().getResourceAsStream("reportes/Carrera.jrxml");
            if (reporteStream == null) {
                throw new RuntimeException("El archivo Carrera.jrxml no se encuentra en la ruta especificada.");
            }

            JasperReport jasperReport = JasperCompileManager.compileReport(reporteStream);
            Map<String, Object> parametros = new HashMap<>();
            JRMapCollectionDataSource dataSource = new JRMapCollectionDataSource(listaReportes);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, dataSource);

            JasperViewer.viewReport(jasperPrint, false);
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos para generar el reporte.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al generar el reporte: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 // Obtener el valor seleccionado del JComboBox
    String selectedCarrera = (String) cbcCarreras.getSelectedItem();
    
    if (selectedCarrera != null) {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        model.addRow(new Object[]{selectedCarrera});
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una carrera.", "Error", JOptionPane.WARNING_MESSAGE);
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbcCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcCarrerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcCarrerasActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbcCarreras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
